# Use root/example as user/password credentials
version: '3.1'

networks:
  voxnet:
    name: voxdocnet
    external: true

services:
  db:
    image: mariadb
    restart: always
    container_name: gel-mariadb
    ports:
      - $DB_PORT:3306
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      voxnet:
        ipv4_address: 172.30.0.6
    volumes:
      - $VAR_LIB_MYSQL:/var/lib/mysql
      - $MYSQL_CONFIG_D:/etc/mysql/conf.d

  adminer:
    image: adminer
    restart: always
    container_name: gel-mariadb-gui
    ports:
      - $GUI_PORT:8080
    networks:
      voxnet:
        ipv4_address: 172.30.0.7
    depends_on:
      - db

volumes:
  mysql-data: